php_version: 8.2
php_extensions:
  - pdo_mysql
  - pdo_sqlite
  - mbstring
  - xml
  - ctype
  - json
  - tokenizer
  - bcmath
  - gd

web_root: public/

compile_commands:
  - npm ci
  - npm run build
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache
